### ISSUE TITLE
Bad toolpath quality

### ISSUE THREAD

**Issue by yvanblanchard** [GuoxinFang/MultiAxis3DPrinting_ToolpathGenerator#2]
Hello,

When processing toolpath on a non-planar surface mesh, quality is very bad.
I modified the surface mesh in MeshLabs in order to get a very good isotropic mesh, and use the smoothing option in your toolpath generator code, but result is still bad:
![image](https://user-images.githubusercontent.com/63931618/194882491-70737cfe-5297-4b2d-827a-690b3dfc9683.png)

![image](https://user-images.githubusercontent.com/63931618/194886192-80a9804d-d548-4311-ac72-bc166db5937d.png)

Here is the input surf mesh:
[surfMesh.zip](https://github.com/GuoxinFang/MultiAxis3DPrinting_ToolpathGenerator/files/9746515/surfMesh.zip)

**Comment by GuoxinFang** [comment]
Hi Yyan, the poor toolpath quality is due to the mesh quality is bad.

I suggest to using Isotropic Explict Remeshing tool provided by meshlab (you might need to upgrade to the latest version). I have also add a loop for refinement to get a better result, but this will increase the computing time in a O(n^3) complexity.

I have done the remeshing for you and the result is quiet good.

[Blade_Slice4_isotropic.zip](https://github.com/GuoxinFang/MultiAxis3DPrinting_ToolpathGenerator/files/9780589/Blade_Slice4_isotropic.zip)

-Guoxin

**Comment by yvanblanchard** [comment]
Thank you Guoxin
